version: '3.8'
services:
    app1:
        container_name: app1
        hostname: app1
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./app1:/var/www/html/
        ports:
            - "5001:80"
    app2:
        container_name: app2
        hostname: app2
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./app2:/var/www/html/
        ports:
            - "5002:80"